#!/usr/bin/env bun
/**
 * ROS 2 interface text (.msg / .srv / .action) → rcl-web TypeScript.
 *
 * Emits declaration files (`.d.ts`) and optional runtime classes (`.ts`)
 * in the `pkg.msg.Type` / `pkg.srv.Name` / `pkg.action.Name` shape used by
 * `rcl-web`. OMG `.idl` is not accepted. Topic encode/decode covers the
 * ROS 2 core interface packages shipped in this repository plus the
 * conformance corpus.
 *
 *   bun run scripts/rosidl-dts.ts --write
 *   bun run scripts/rosidl-dts.ts --check
 *   bun run scripts/rosidl-dts.ts --package path/to/pkg --out out/pkg.d.ts
 *   bun run scripts/rosidl-dts.ts --package path/to/pkg --out out/pkg.ts
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { selectInterfaceSection, type RootKind } from "./ros-interface-text.ts";

export const PROJECT_PACKAGE_RELS = [
  "typescript/rosidl/action_msgs",
  "typescript/rosidl/builtin_interfaces",
  "typescript/rosidl/composition_interfaces",
  "typescript/rosidl/diagnostic_msgs",
  "typescript/rosidl/geometry_msgs",
  "typescript/rosidl/lifecycle_msgs",
  "typescript/rosidl/nav_msgs",
  "typescript/rosidl/rcl_interfaces",
  "typescript/rosidl/rosgraph_msgs",
  "typescript/rosidl/sensor_msgs",
  "typescript/rosidl/shape_msgs",
  "typescript/rosidl/statistics_msgs",
  "typescript/rosidl/std_msgs",
  "typescript/rosidl/std_srvs",
  "typescript/rosidl/stereo_msgs",
  "typescript/rosidl/tf2_msgs",
  "typescript/rosidl/trajectory_msgs",
  "typescript/rosidl/type_description_interfaces",
  "typescript/rosidl/unique_identifier_msgs",
  "typescript/rosidl/visualization_msgs",
  "conformance/interfaces/rclweb_cdr_interfaces",
] as const;

export const TS_OUT_REL = "typescript/src/interfaces.generated.ts";
export const DTS_OUT_REL = "typescript/generated/rosidl.d.ts";

export const PRIMITIVES = [
  "bool",
  "byte",
  "char",
  "float32",
  "float64",
  "int8",
  "uint8",
  "int16",
  "uint16",
  "int32",
  "uint32",
  "int64",
  "uint64",
] as const;

export type PrimitiveName = (typeof PRIMITIVES)[number];

const PRIMITIVE_SET = new Set<string>(PRIMITIVES);

export type ArrayShape =
  | { kind: "none" }
  | { kind: "unbounded" }
  | { kind: "fixed"; size: number }
  | { kind: "bounded"; size: number };

export type BaseType =
  | { kind: "primitive"; name: PrimitiveName }
  | { kind: "string"; wide: boolean; bound?: number }
  | { kind: "named"; raw: string };

export type FieldType = {
  base: BaseType;
  array: ArrayShape;
};

export type Field = {
  name: string;
  type: FieldType;
  defaultText?: string;
};

export type Constant = {
  name: string;
  type: FieldType;
  value: string;
};

export type ParsedSection = {
  fields: Field[];
  constants: Constant[];
};

export type MessageDef = {
  typeName: string;
  packageName: string;
  shortName: string;
  fields: Field[];
  constants: Constant[];
};

export type ServiceDef = {
  typeName: string;
  packageName: string;
  shortName: string;
  request: ParsedSection;
  response: ParsedSection;
};

export type ActionDef = {
  typeName: string;
  packageName: string;
  shortName: string;
  goal: ParsedSection;
  result: ParsedSection;
  feedback: ParsedSection;
};

export type PackageInterfaces = {
  name: string;
  dir: string;
  messages: MessageDef[];
  services: ServiceDef[];
  actions: ActionDef[];
};

export type IrField = {
  name: string;
  tsType: string;
  defaultExpr: string;
};

export type IrLayoutArray =
  | { kind: "none" }
  | { kind: "unbounded" }
  | { kind: "fixed"; size: number }
  | { kind: "bounded"; size: number };

export type IrLayoutField =
  | { name: string; kind: "prim"; prim: PrimitiveName; array: IrLayoutArray }
  | { name: string; kind: "str"; wide: boolean; bound?: number; array: IrLayoutArray }
  | { name: string; kind: "named"; typeName: string; array: IrLayoutArray };

export type IrClass = {
  className: string;
  nsKey: string;
  typeName: string;
  fields: IrField[];
  layout: IrLayoutField[];
  constants: Array<{ name: string; tsType: string; valueExpr: string }>;
  dependsOn: string[];
};

export type IrService = {
  className: string;
  nsKey: string;
  typeName: string;
  request: IrClass;
  response: IrClass;
};

export type IrAction = {
  className: string;
  nsKey: string;
  typeName: string;
  goal: IrClass;
  result: IrClass;
  feedback: IrClass;
};

export type IrPackage = {
  name: string;
  messages: IrClass[];
  services: IrService[];
  actions: IrAction[];
};

export type BuildOk = { ok: true; packages: IrPackage[]; ts: string; dts: string };
export type BuildErr = { ok: false; reason: string };
export type BuildResult = BuildOk | BuildErr;

export const REPO_BANNER = `/**
 * Generated by scripts/rosidl-dts.ts from ROS 2 interface files.
 * Do not edit by hand. Regenerate with \`bun run rosidl-dts:write\`.
 */

`;

export const USER_BANNER = `/**
 * Generated from ROS 2 interface files. Do not edit by hand.
 * Regenerate with \`npx rcl-web gen\`.
 */

`;

export const USER_HELP = `Generate rcl-web TypeScript from a ROS 2 interface package.

  npx rcl-web gen --package ./my_interfaces --out src/generated/my_interfaces.ts

Then import the classes the same way you import std_msgs:

  import { my_interfaces } from "./generated/my_interfaces.ts";
  const msg = new my_interfaces.msg.Status();

Options:
  --package DIR   ROS package directory (msg/, srv/, action/)
  --root DIR      directory of interface packages
  --out FILE      .ts (runtime classes) or .d.ts (types only)
  --out DIR       one file per package

OMG .idl is not accepted. Topic encode/decode covers the ROS 2 core
interface packages shipped in rcl-web plus the conformance corpus.
Other workspace types still send Uint8Array CDR.
`;

function fail(reason: string): BuildErr {
  return { ok: false, reason };
}

export function isPrimitive(name: string): name is PrimitiveName {
  return PRIMITIVE_SET.has(name);
}

export function parseTypeExpr(
  expr: string,
): { ok: true; type: FieldType } | { ok: false; reason: string } {
  const trimmed = expr.trim();
  if (trimmed.length === 0) return { ok: false, reason: "empty type" };

  let base = trimmed;
  let array: ArrayShape = { kind: "none" };
  const bounded = trimmed.match(/^(.*)\[<=(\d+)\]$/);
  const fixed = trimmed.match(/^(.*)\[(\d+)\]$/);
  const unbounded = trimmed.match(/^(.*)\[\]$/);
  if (bounded) {
    base = bounded[1]!;
    const size = Number(bounded[2]);
    if (!Number.isInteger(size) || size < 1) {
      return { ok: false, reason: `invalid bounded array size in ${expr}` };
    }
    array = { kind: "bounded", size };
  } else if (fixed) {
    base = fixed[1]!;
    const size = Number(fixed[2]);
    if (!Number.isInteger(size) || size < 1) {
      return { ok: false, reason: `invalid fixed array size in ${expr}` };
    }
    array = { kind: "fixed", size };
  } else if (unbounded) {
    base = unbounded[1]!;
    array = { kind: "unbounded" };
  }

  if (isPrimitive(base)) {
    return { ok: true, type: { base: { kind: "primitive", name: base }, array } };
  }
  const stringMatch = base.match(/^(w?string)(?:<=(\d+))?$/);
  if (stringMatch) {
    const bound = stringMatch[2] === undefined ? undefined : Number(stringMatch[2]);
    if (bound !== undefined && (!Number.isInteger(bound) || bound < 1)) {
      return { ok: false, reason: `invalid string bound in ${expr}` };
    }
    return {
      ok: true,
      type: { base: { kind: "string", wide: stringMatch[1] === "wstring", bound }, array },
    };
  }
  if (/^[A-Za-z_][A-Za-z0-9_]*(\/[A-Za-z_][A-Za-z0-9_]*){0,2}$/.test(base)) {
    return { ok: true, type: { base: { kind: "named", raw: base }, array } };
  }
  return { ok: false, reason: `unsupported type ${expr}` };
}

/** True when `=` assigns a constant, not a ROS `<=` bound. */
export function isConstantLine(line: string): boolean {
  return line.replaceAll("<=", "").includes("=");
}

export function parseInterfaceSection(
  section: string,
): { ok: true; parsed: ParsedSection } | { ok: false; reason: string } {
  const fields: Field[] = [];
  const constants: Constant[] = [];
  for (const rawLine of section.split(/\r?\n/)) {
    const withoutComment = rawLine.replace(/#.*$/, "");
    const line = withoutComment.trim();
    if (line.length === 0) continue;
    if (isConstantLine(line)) {
      const eq = line.indexOf("=");
      const left = line.slice(0, eq)!.trim();
      const value = line.slice(eq + 1)!.trim();
      const tokens = left.split(/\s+/).filter((t) => t.length > 0);
      if (tokens.length < 2) {
        return { ok: false, reason: `malformed constant line: ${rawLine}` };
      }
      const typeExpr = tokens[0]!;
      const name = tokens[tokens.length - 1]!;
      if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
        return { ok: false, reason: `invalid constant name: ${name}` };
      }
      const parsedType = parseTypeExpr(typeExpr);
      if (!parsedType.ok) return parsedType;
      if (value.length === 0) {
        return { ok: false, reason: `constant ${name} has empty value` };
      }
      constants.push({ name, type: parsedType.type, value });
      continue;
    }
    const tokens = line.split(/\s+/).filter((t) => t.length > 0);
    if (tokens.length < 2) {
      return { ok: false, reason: `malformed field line: ${rawLine}` };
    }
    const parsedType = parseTypeExpr(tokens[0]!);
    if (!parsedType.ok) return parsedType;
    const name = tokens[1]!;
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
      return { ok: false, reason: `invalid field name: ${name}` };
    }
    const field: Field = { name, type: parsedType.type };
    if (tokens.length > 2) field.defaultText = tokens.slice(2).join(" ");
    fields.push(field);
  }
  return { ok: true, parsed: { fields, constants } };
}

function sectionOrFail(
  content: string,
  kind: RootKind,
): { ok: true; parsed: ParsedSection } | { ok: false; reason: string } {
  const selected = selectInterfaceSection(content, kind);
  if (!selected.ok) return selected;
  return parseInterfaceSection(selected.section);
}

export function packageNameFromXml(xml: string): string | undefined {
  const match = xml.match(/<name>\s*([A-Za-z_][A-Za-z0-9_]*)\s*<\/name>/);
  return match?.[1];
}

async function listInterfaceFiles(
  dir: string,
  kind: "msg" | "srv" | "action",
): Promise<string[]> {
  const sub = path.join(dir, kind);
  return listFilesWithExt(sub, `.${kind}`);
}

async function listFilesWithExt(dir: string, ext: string): Promise<string[]> {
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return [];
  }
  return entries
    .filter((name) => name.endsWith(ext) && !name.startsWith("."))
    .map((name) => path.join(dir, name))
    .sort();
}

export async function loadPackage(
  dir: string,
): Promise<{ ok: true; pkg: PackageInterfaces } | { ok: false; reason: string }> {
  const abs = path.resolve(dir);
  let name = path.basename(abs);
  try {
    const xml = await readFile(path.join(abs, "package.xml"), "utf8");
    name = packageNameFromXml(xml) ?? name;
  } catch {
    // directory name is the package name
  }

  const messages: MessageDef[] = [];
  for (const file of await listInterfaceFiles(abs, "msg")) {
    const content = await readFile(file, "utf8");
    const parsed = parseInterfaceSection(content);
    if (!parsed.ok) return { ok: false, reason: `${file}: ${parsed.reason}` };
    const shortName = path.basename(file, ".msg");
    messages.push({
      typeName: `${name}/msg/${shortName}`,
      packageName: name,
      shortName,
      fields: parsed.parsed.fields,
      constants: parsed.parsed.constants,
    });
  }

  const services: ServiceDef[] = [];
  for (const file of await listInterfaceFiles(abs, "srv")) {
    const content = await readFile(file, "utf8");
    const request = sectionOrFail(content, "srv_request");
    if (!request.ok) return { ok: false, reason: `${file}: ${request.reason}` };
    const response = sectionOrFail(content, "srv_response");
    if (!response.ok) return { ok: false, reason: `${file}: ${response.reason}` };
    const shortName = path.basename(file, ".srv");
    services.push({
      typeName: `${name}/srv/${shortName}`,
      packageName: name,
      shortName,
      request: request.parsed,
      response: response.parsed,
    });
  }

  const actions: ActionDef[] = [];
  for (const file of await listInterfaceFiles(abs, "action")) {
    const content = await readFile(file, "utf8");
    const goal = sectionOrFail(content, "action_goal");
    if (!goal.ok) return { ok: false, reason: `${file}: ${goal.reason}` };
    const result = sectionOrFail(content, "action_result");
    if (!result.ok) return { ok: false, reason: `${file}: ${result.reason}` };
    const feedback = sectionOrFail(content, "action_feedback");
    if (!feedback.ok) return { ok: false, reason: `${file}: ${feedback.reason}` };
    const shortName = path.basename(file, ".action");
    actions.push({
      typeName: `${name}/action/${shortName}`,
      packageName: name,
      shortName,
      goal: goal.parsed,
      result: result.parsed,
      feedback: feedback.parsed,
    });
  }

  const idlFiles = (
    await Promise.all([
      listFilesWithExt(abs, ".idl"),
      listFilesWithExt(path.join(abs, "msg"), ".idl"),
      listFilesWithExt(path.join(abs, "srv"), ".idl"),
      listFilesWithExt(path.join(abs, "action"), ".idl"),
    ])
  ).flat();
  if (idlFiles.length > 0) {
    return {
      ok: false,
      reason: `${abs}: OMG .idl is not accepted; use .msg / .srv / .action`,
    };
  }
  if (messages.length === 0 && services.length === 0 && actions.length === 0) {
    return { ok: false, reason: `${abs}: no .msg / .srv / .action files` };
  }
  return { ok: true, pkg: { name, dir: abs, messages, services, actions } };
}

export async function loadPackages(
  dirs: string[],
): Promise<{ ok: true; packages: PackageInterfaces[] } | { ok: false; reason: string }> {
  const packages: PackageInterfaces[] = [];
  const seen = new Set<string>();
  for (const dir of dirs) {
    const loaded = await loadPackage(dir);
    if (!loaded.ok) return loaded;
    if (seen.has(loaded.pkg.name)) {
      return { ok: false, reason: `duplicate package ${loaded.pkg.name}` };
    }
    seen.add(loaded.pkg.name);
    packages.push(loaded.pkg);
  }
  packages.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  return { ok: true, packages };
}

export async function discoverPackages(root: string): Promise<string[]> {
  const abs = path.resolve(root);
  const entries = await readdir(abs, { withFileTypes: true });
  const dirs: string[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith(".")) continue;
    const candidate = path.join(abs, entry.name);
    const kinds = await Promise.all([
      listInterfaceFiles(candidate, "msg"),
      listInterfaceFiles(candidate, "srv"),
      listInterfaceFiles(candidate, "action"),
    ]);
    if (kinds.some((files) => files.length > 0)) dirs.push(candidate);
  }
  dirs.sort();
  return dirs;
}

type CatalogEntry = { typeName: string; shortName: string; packageName: string };

function catalogOf(packages: PackageInterfaces[]): Map<string, CatalogEntry> {
  const catalog = new Map<string, CatalogEntry>();
  const add = (typeName: string, packageName: string, shortName: string) => {
    catalog.set(typeName, { typeName, packageName, shortName });
  };
  for (const pkg of packages) {
    for (const msg of pkg.messages) add(msg.typeName, msg.packageName, msg.shortName);
    for (const srv of pkg.services) {
      add(`${srv.typeName}_Request`, srv.packageName, `${srv.shortName}_Request`);
      add(`${srv.typeName}_Response`, srv.packageName, `${srv.shortName}_Response`);
    }
    for (const action of pkg.actions) {
      add(`${action.typeName}_Goal`, action.packageName, `${action.shortName}_Goal`);
      add(`${action.typeName}_Result`, action.packageName, `${action.shortName}_Result`);
      add(`${action.typeName}_Feedback`, action.packageName, `${action.shortName}_Feedback`);
    }
  }
  return catalog;
}

export function resolveNamedType(
  raw: string,
  currentPackage: string,
  catalog: Map<string, CatalogEntry>,
): { ok: true; typeName: string } | { ok: false; reason: string } {
  if (raw.includes("/msg/") || raw.includes("/srv/") || raw.includes("/action/")) {
    if (!catalog.has(raw)) return { ok: false, reason: `unknown type ${raw}` };
    return { ok: true, typeName: raw };
  }
  if (raw.includes("/")) {
    const [pkg, name] = raw.split("/");
    const candidates = [`${pkg}/msg/${name}`, `${pkg}/srv/${name}`, `${pkg}/action/${name}`];
    const hits = candidates.filter((c) => catalog.has(c));
    if (hits.length === 1) return { ok: true, typeName: hits[0]! };
    if (hits.length > 1) {
      return { ok: false, reason: `ambiguous type ${raw}` };
    }
    return { ok: false, reason: `unknown type ${raw}` };
  }
  const samePkg = [
    `${currentPackage}/msg/${raw}`,
    `${currentPackage}/srv/${raw}`,
    `${currentPackage}/action/${raw}`,
  ].filter((c) => catalog.has(c));
  if (samePkg.length === 1) return { ok: true, typeName: samePkg[0]! };
  if (samePkg.length > 1) return { ok: false, reason: `ambiguous type ${raw}` };
  const global = [...catalog.values()].filter((e) => e.shortName === raw);
  if (global.length === 1) return { ok: true, typeName: global[0]!.typeName };
  if (global.length > 1) return { ok: false, reason: `ambiguous type ${raw}` };
  return { ok: false, reason: `unknown type ${raw}` };
}

function allocateClassNames(catalog: Map<string, CatalogEntry>): Map<string, string> {
  const counts = new Map<string, number>();
  for (const entry of catalog.values()) {
    counts.set(entry.shortName, (counts.get(entry.shortName) ?? 0) + 1);
  }
  const names = new Map<string, string>();
  for (const entry of catalog.values()) {
    if ((counts.get(entry.shortName) ?? 0) === 1) {
      names.set(entry.typeName, entry.shortName);
    } else {
      names.set(entry.typeName, `${pascalPackage(entry.packageName)}${entry.shortName}`);
    }
  }
  return names;
}

export function pascalPackage(name: string): string {
  return name
    .split("_")
    .filter((part) => part.length > 0)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
}

function isBytePrimitive(name: PrimitiveName): boolean {
  return name === "uint8" || name === "byte";
}

export function tsTypeFor(
  type: FieldType,
  classNameOf: (typeName: string) => string,
): string {
  const inner = (() => {
    if (type.base.kind === "primitive") {
      if (type.base.name === "bool") return "boolean";
      if (type.base.name === "int64" || type.base.name === "uint64") return "bigint";
      return "number";
    }
    if (type.base.kind === "string") return "string";
    return classNameOf(type.base.raw);
  })();

  if (type.array.kind === "none") return inner;
  if (type.base.kind === "primitive" && isBytePrimitive(type.base.name)) {
    return "Uint8Array";
  }
  if (type.array.kind === "fixed" && type.array.size <= 16) {
    return `[${Array.from({ length: type.array.size }, () => inner).join(", ")}]`;
  }
  return `${inner}[]`;
}

function defaultForScalar(type: FieldType, classNameOf: (typeName: string) => string): string {
  if (type.base.kind === "primitive") {
    if (type.base.name === "bool") return "false";
    if (type.base.name === "int64" || type.base.name === "uint64") return "0n";
    return "0";
  }
  if (type.base.kind === "string") return '""';
  return `new ${classNameOf(type.base.raw)}()`;
}

export function defaultExprFor(
  type: FieldType,
  classNameOf: (typeName: string) => string,
): string {
  if (type.array.kind === "none") return defaultForScalar(type, classNameOf);
  if (type.base.kind === "primitive" && isBytePrimitive(type.base.name)) {
    return "new Uint8Array()";
  }
  if (type.array.kind === "fixed" && type.array.size <= 16) {
    const one = defaultForScalar({ ...type, array: { kind: "none" } }, classNameOf);
    return `[${Array.from({ length: type.array.size }, () => one).join(", ")}]`;
  }
  return "[]";
}

function constantTsType(type: FieldType): string {
  if (type.base.kind === "primitive") {
    if (type.base.name === "bool") return "boolean";
    if (type.base.name === "int64" || type.base.name === "uint64") return "bigint";
    return "number";
  }
  if (type.base.kind === "string") return "string";
  return "number";
}

export function constantValueExpr(value: string, type: FieldType): string {
  const trimmed = value.trim();
  if (type.base.kind === "string") {
    if (/^".*"$/.test(trimmed) || /^'.*'$/.test(trimmed)) return trimmed;
    return JSON.stringify(trimmed);
  }
  if (type.base.kind === "primitive" && type.base.name === "bool") {
    if (trimmed === "1" || trimmed === "true") return "true";
    return "false";
  }
  if (type.base.kind === "primitive" && (type.base.name === "int64" || type.base.name === "uint64")) {
    return trimmed.endsWith("n") ? trimmed : `${trimmed}n`;
  }
  return trimmed;
}

function resolveFieldTypes(
  section: ParsedSection,
  currentPackage: string,
  catalog: Map<string, CatalogEntry>,
): { ok: true; fields: Field[] } | { ok: false; reason: string } {
  const fields: Field[] = [];
  for (const field of section.fields) {
    if (field.type.base.kind !== "named") {
      fields.push(field);
      continue;
    }
    const resolved = resolveNamedType(field.type.base.raw, currentPackage, catalog);
    if (!resolved.ok) return resolved;
    fields.push({
      ...field,
      type: { ...field.type, base: { kind: "named", raw: resolved.typeName } },
    });
  }
  return { ok: true, fields };
}

function layoutFieldOf(field: Field): IrLayoutField {
  const array = field.type.array;
  if (field.type.base.kind === "primitive") {
    return { name: field.name, kind: "prim", prim: field.type.base.name, array };
  }
  if (field.type.base.kind === "string") {
    return {
      name: field.name,
      kind: "str",
      wide: field.type.base.wide,
      ...(field.type.base.bound !== undefined ? { bound: field.type.base.bound } : {}),
      array,
    };
  }
  return { name: field.name, kind: "named", typeName: field.type.base.raw, array };
}

function classFromSection(
  typeName: string,
  className: string,
  nsKey: string,
  section: ParsedSection,
  currentPackage: string,
  catalog: Map<string, CatalogEntry>,
  classNames: Map<string, string>,
): { ok: true; ir: IrClass } | { ok: false; reason: string } {
  const resolved = resolveFieldTypes(section, currentPackage, catalog);
  if (!resolved.ok) return resolved;
  const classNameOf = (tn: string) => {
    const name = classNames.get(tn);
    if (!name) throw new Error(`missing class name for ${tn}`);
    return name;
  };
  const fields: IrField[] = resolved.fields.map((field) => ({
    name: field.name,
    tsType: tsTypeFor(field.type, classNameOf),
    defaultExpr: defaultExprFor(field.type, classNameOf),
  }));
  const constants = section.constants.map((c) => ({
    name: c.name,
    tsType: constantTsType(c.type),
    valueExpr: constantValueExpr(c.value, c.type),
  }));
  const dependsOn = resolved.fields
    .filter((f) => f.type.base.kind === "named")
    .map((f) => classNames.get((f.type.base as { raw: string }).raw)!)
    .filter((n) => n && n !== className);
  return {
    ok: true,
    ir: {
      className,
      nsKey,
      typeName,
      fields,
      layout: resolved.fields.map(layoutFieldOf),
      constants,
      dependsOn: [...new Set(dependsOn)],
    },
  };
}

function allocateBundleName(shortName: string, packageName: string, used: Set<string>): string {
  if (!used.has(shortName)) {
    used.add(shortName);
    return shortName;
  }
  const prefixed = `${pascalPackage(packageName)}${shortName}`;
  used.add(prefixed);
  return prefixed;
}

export function buildIr(
  packages: PackageInterfaces[],
  banner = REPO_BANNER,
): BuildResult {
  const catalog = catalogOf(packages);
  const classNames = allocateClassNames(catalog);
  const usedNames = new Set<string>(classNames.values());
  const irPackages: IrPackage[] = [];

  for (const pkg of packages) {
    const messages: IrClass[] = [];
    for (const msg of pkg.messages) {
      const className = classNames.get(msg.typeName);
      if (!className) return fail(`missing class name for ${msg.typeName}`);
      const built = classFromSection(
        msg.typeName,
        className,
        msg.shortName,
        { fields: msg.fields, constants: msg.constants },
        pkg.name,
        catalog,
        classNames,
      );
      if (!built.ok) return built;
      messages.push(built.ir);
    }
    messages.sort((a, b) => (a.typeName < b.typeName ? -1 : 1));

    const services: IrService[] = [];
    for (const srv of pkg.services) {
      const reqName = classNames.get(`${srv.typeName}_Request`);
      const resName = classNames.get(`${srv.typeName}_Response`);
      if (!reqName || !resName) return fail(`missing service class for ${srv.typeName}`);
      const request = classFromSection(
        `${srv.typeName}_Request`,
        reqName,
        `${srv.shortName}_Request`,
        srv.request,
        pkg.name,
        catalog,
        classNames,
      );
      if (!request.ok) return request;
      const response = classFromSection(
        `${srv.typeName}_Response`,
        resName,
        `${srv.shortName}_Response`,
        srv.response,
        pkg.name,
        catalog,
        classNames,
      );
      if (!response.ok) return response;
      services.push({
        className: allocateBundleName(srv.shortName, pkg.name, usedNames),
        nsKey: srv.shortName,
        typeName: srv.typeName,
        request: request.ir,
        response: response.ir,
      });
    }
    services.sort((a, b) => (a.typeName < b.typeName ? -1 : 1));

    const actions: IrAction[] = [];
    for (const action of pkg.actions) {
      const goalName = classNames.get(`${action.typeName}_Goal`);
      const resultName = classNames.get(`${action.typeName}_Result`);
      const feedbackName = classNames.get(`${action.typeName}_Feedback`);
      if (!goalName || !resultName || !feedbackName) {
        return fail(`missing action class for ${action.typeName}`);
      }
      const goal = classFromSection(
        `${action.typeName}_Goal`,
        goalName,
        `${action.shortName}_Goal`,
        action.goal,
        pkg.name,
        catalog,
        classNames,
      );
      if (!goal.ok) return goal;
      const result = classFromSection(
        `${action.typeName}_Result`,
        resultName,
        `${action.shortName}_Result`,
        action.result,
        pkg.name,
        catalog,
        classNames,
      );
      if (!result.ok) return result;
      const feedback = classFromSection(
        `${action.typeName}_Feedback`,
        feedbackName,
        `${action.shortName}_Feedback`,
        action.feedback,
        pkg.name,
        catalog,
        classNames,
      );
      if (!feedback.ok) return feedback;
      actions.push({
        className: allocateBundleName(action.shortName, pkg.name, usedNames),
        nsKey: action.shortName,
        typeName: action.typeName,
        goal: goal.ir,
        result: result.ir,
        feedback: feedback.ir,
      });
    }
    actions.sort((a, b) => (a.typeName < b.typeName ? -1 : 1));

    irPackages.push({ name: pkg.name, messages, services, actions });
  }

  return {
    ok: true,
    packages: irPackages,
    ts: emitTs(irPackages, banner),
    dts: emitDts(irPackages, banner),
  };
}

function allClasses(packages: IrPackage[]): IrClass[] {
  const classes: IrClass[] = [];
  for (const pkg of packages) {
    classes.push(...pkg.messages);
    for (const srv of pkg.services) classes.push(srv.request, srv.response);
    for (const action of pkg.actions) {
      classes.push(action.goal, action.result, action.feedback);
    }
  }
  return classes;
}

export function topoSortClasses(classes: IrClass[]): IrClass[] {
  const byName = new Map(classes.map((c) => [c.className, c]));
  const visiting = new Set<string>();
  const visited = new Set<string>();
  const out: IrClass[] = [];
  const visit = (name: string) => {
    if (visited.has(name)) return;
    if (visiting.has(name)) return;
    visiting.add(name);
    const cls = byName.get(name);
    if (cls) {
      const deps = [...cls.dependsOn].sort();
      for (const dep of deps) visit(dep);
      out.push(cls);
    }
    visiting.delete(name);
    visited.add(name);
  };
  const names = [...byName.keys()].sort();
  for (const name of names) visit(name);
  return out;
}

function emitClassTs(cls: IrClass): string {
  const lines = [`export class ${cls.className} {`];
  lines.push(`  static readonly typeName = "${cls.typeName}" as const;`);
  for (const c of cls.constants) {
    lines.push(`  static readonly ${c.name} = ${c.valueExpr};`);
  }
  for (const field of cls.fields) {
    const needsAnnot =
      field.defaultExpr.startsWith("[") || field.tsType.includes("[]") || field.tsType.includes("[");
    if (needsAnnot && !field.defaultExpr.startsWith("new ")) {
      lines.push(`  ${field.name}: ${field.tsType} = ${field.defaultExpr};`);
    } else {
      lines.push(`  ${field.name} = ${field.defaultExpr};`);
    }
  }
  lines.push("}");
  return lines.join("\n");
}

function emitClassDts(cls: IrClass): string {
  const lines = [`export declare class ${cls.className} {`];
  lines.push(`  static readonly typeName: "${cls.typeName}";`);
  for (const c of cls.constants) {
    lines.push(`  static readonly ${c.name}: ${c.tsType};`);
  }
  for (const field of cls.fields) {
    lines.push(`  ${field.name}: ${field.tsType};`);
  }
  lines.push("  constructor();");
  lines.push("}");
  return lines.join("\n");
}

function nsBinding(nsKey: string, className: string): string {
  return nsKey === className ? className : `${nsKey}: ${className}`;
}

function emitNamespacesTs(packages: IrPackage[]): string {
  const blocks: string[] = [];
  for (const pkg of packages) {
    const msg = pkg.messages.map((m) => nsBinding(m.nsKey, m.className)).join(", ");
    const srv = pkg.services.map((s) => nsBinding(s.nsKey, s.className)).join(", ");
    const action = pkg.actions.map((a) => nsBinding(a.nsKey, a.className)).join(", ");
    const parts: string[] = [];
    if (pkg.messages.length) parts.push(`  msg: { ${msg} },`);
    if (pkg.services.length) parts.push(`  srv: { ${srv} },`);
    if (pkg.actions.length) parts.push(`  action: { ${action} },`);
    blocks.push(`export const ${pkg.name} = {\n${parts.join("\n")}\n};`);
  }
  return blocks.join("\n\n");
}

function emitNamespacesDts(packages: IrPackage[]): string {
  const blocks: string[] = [];
  for (const pkg of packages) {
    const parts: string[] = [];
    if (pkg.messages.length) {
      const rows = pkg.messages
        .map((m) => `    readonly ${m.nsKey}: typeof ${m.className};`)
        .join("\n");
      parts.push(`  readonly msg: {\n${rows}\n  };`);
    }
    if (pkg.services.length) {
      const rows = pkg.services
        .map((s) => `    readonly ${s.nsKey}: typeof ${s.className};`)
        .join("\n");
      parts.push(`  readonly srv: {\n${rows}\n  };`);
    }
    if (pkg.actions.length) {
      const rows = pkg.actions
        .map((a) => `    readonly ${a.nsKey}: typeof ${a.className};`)
        .join("\n");
      parts.push(`  readonly action: {\n${rows}\n  };`);
    }
    blocks.push(`export declare const ${pkg.name}: {\n${parts.join("\n")}\n};`);
  }
  return blocks.join("\n\n");
}

function emitServiceConstTs(srv: IrService): string {
  return [
    `export const ${srv.className} = {`,
    `  typeName: "${srv.typeName}" as const,`,
    `  Request: ${srv.request.className},`,
    `  Response: ${srv.response.className},`,
    `};`,
  ].join("\n");
}

function emitServiceConstDts(srv: IrService): string {
  return [
    `export declare const ${srv.className}: {`,
    `  readonly typeName: "${srv.typeName}";`,
    `  readonly Request: typeof ${srv.request.className};`,
    `  readonly Response: typeof ${srv.response.className};`,
    `};`,
  ].join("\n");
}

function emitActionConstTs(action: IrAction): string {
  return [
    `export const ${action.className} = {`,
    `  typeName: "${action.typeName}" as const,`,
    `  Goal: ${action.goal.className},`,
    `  Result: ${action.result.className},`,
    `  Feedback: ${action.feedback.className},`,
    `};`,
  ].join("\n");
}

function emitActionConstDts(action: IrAction): string {
  return [
    `export declare const ${action.className}: {`,
    `  readonly typeName: "${action.typeName}";`,
    `  readonly Goal: typeof ${action.goal.className};`,
    `  readonly Result: typeof ${action.result.className};`,
    `  readonly Feedback: typeof ${action.feedback.className};`,
    `};`,
  ].join("\n");
}

function emitCatalogTs(packages: IrPackage[]): string {
  const classes = allClasses(packages);
  const layoutEntries = classes
    .map((cls) => `  ${JSON.stringify(cls.typeName)}: ${JSON.stringify(cls.layout)}`)
    .join(",\n");
  const msgNames = packages
    .flatMap((pkg) => pkg.messages.map((m) => m.typeName))
    .sort()
    .map((name) => `  ${JSON.stringify(name)},`)
    .join("\n");
  const allNames = classes
    .map((cls) => cls.typeName)
    .sort()
    .map((name) => `  ${JSON.stringify(name)},`)
    .join("\n");
  const opEntries: string[] = [];
  for (const pkg of packages) {
    for (const srv of pkg.services) {
      opEntries.push(
        `  ${JSON.stringify(srv.typeName)}: { Request: ${JSON.stringify(srv.request.typeName)}, Response: ${JSON.stringify(srv.response.typeName)} }`,
      );
    }
    for (const action of pkg.actions) {
      opEntries.push(
        `  ${JSON.stringify(action.typeName)}: { Goal: ${JSON.stringify(action.goal.typeName)}, Result: ${JSON.stringify(action.result.typeName)}, Feedback: ${JSON.stringify(action.feedback.typeName)} }`,
      );
    }
  }
  opEntries.sort();
  const ctorCases = classes
    .map((cls) => `    case ${JSON.stringify(cls.typeName)}: return new ${cls.className}();`)
    .join("\n");
  return [
    "export type GeneratedLayoutArray =",
    '  | { kind: "none" }',
    '  | { kind: "unbounded" }',
    '  | { kind: "fixed"; size: number }',
    '  | { kind: "bounded"; size: number };',
    "",
    "export type GeneratedLayoutField =",
    '  | { name: string; kind: "prim"; prim: string; array: GeneratedLayoutArray }',
    '  | { name: string; kind: "str"; wide: boolean; bound?: number; array: GeneratedLayoutArray }',
    '  | { name: string; kind: "named"; typeName: string; array: GeneratedLayoutArray };',
    "",
    "export const GENERATED_LAYOUTS: { readonly [typeName: string]: readonly GeneratedLayoutField[] } = {",
    layoutEntries,
    "};",
    "",
    "export const GENERATED_MSG_TYPE_NAMES: ReadonlySet<string> = new Set([",
    msgNames,
    "]);",
    "",
    "export const GENERATED_TYPE_NAMES: ReadonlySet<string> = new Set([",
    allNames,
    "]);",
    "",
    "export const GENERATED_OP_TYPES: {",
    "  readonly [typeName: string]: {",
    "    readonly Request?: string;",
    "    readonly Response?: string;",
    "    readonly Goal?: string;",
    "    readonly Result?: string;",
    "    readonly Feedback?: string;",
    "  };",
    "} = {",
    opEntries.join(",\n"),
    "};",
    "",
    "export function createGenerated(typeName: string): object | undefined {",
    "  switch (typeName) {",
    ctorCases,
    "    default: return undefined;",
    "  }",
    "}",
  ].join("\n");
}

function emitCatalogDts(packages: IrPackage[]): string {
  return [
    "export type GeneratedLayoutArray =",
    '  | { kind: "none" }',
    '  | { kind: "unbounded" }',
    '  | { kind: "fixed"; size: number }',
    '  | { kind: "bounded"; size: number };',
    "",
    "export type GeneratedLayoutField =",
    '  | { name: string; kind: "prim"; prim: string; array: GeneratedLayoutArray }',
    '  | { name: string; kind: "str"; wide: boolean; bound?: number; array: GeneratedLayoutArray }',
    '  | { name: string; kind: "named"; typeName: string; array: GeneratedLayoutArray };',
    "",
    "export declare const GENERATED_LAYOUTS: {",
    "  readonly [typeName: string]: readonly GeneratedLayoutField[];",
    "};",
    "",
    "export declare const GENERATED_MSG_TYPE_NAMES: ReadonlySet<string>;",
    "",
    "export declare const GENERATED_TYPE_NAMES: ReadonlySet<string>;",
    "",
    "export declare const GENERATED_OP_TYPES: {",
    "  readonly [typeName: string]: {",
    "    readonly Request?: string;",
    "    readonly Response?: string;",
    "    readonly Goal?: string;",
    "    readonly Result?: string;",
    "    readonly Feedback?: string;",
    "  };",
    "};",
    "",
    "export declare function createGenerated(typeName: string): object | undefined;",
  ].join("\n");
}

export function emitTs(packages: IrPackage[], banner = REPO_BANNER): string {
  const classes = topoSortClasses(allClasses(packages));
  const parts = [banner.trimEnd(), ""];
  for (const cls of classes) {
    parts.push(emitClassTs(cls), "");
  }
  for (const pkg of packages) {
    for (const srv of pkg.services) {
      parts.push(emitServiceConstTs(srv), "");
    }
    for (const action of pkg.actions) {
      parts.push(emitActionConstTs(action), "");
    }
  }
  parts.push(emitNamespacesTs(packages), "");
  parts.push(emitCatalogTs(packages), "");
  return `${parts.join("\n").trimEnd()}\n`;
}

export function emitDts(packages: IrPackage[], banner = REPO_BANNER): string {
  const classes = topoSortClasses(allClasses(packages));
  const parts = [banner.trimEnd(), ""];
  for (const cls of classes) {
    parts.push(emitClassDts(cls), "");
  }
  for (const pkg of packages) {
    for (const srv of pkg.services) {
      parts.push(emitServiceConstDts(srv), "");
    }
    for (const action of pkg.actions) {
      parts.push(emitActionConstDts(action), "");
    }
  }
  parts.push(emitNamespacesDts(packages), "");
  parts.push(emitCatalogDts(packages), "");
  return `${parts.join("\n").trimEnd()}\n`;
}

export async function buildFromDirs(
  dirs: string[],
  banner = REPO_BANNER,
): Promise<BuildResult> {
  const loaded = await loadPackages(dirs);
  if (!loaded.ok) return loaded;
  return buildIr(loaded.packages, banner);
}

export async function buildProject(root: string): Promise<BuildResult> {
  const dirs = PROJECT_PACKAGE_RELS.map((rel) => path.join(root, rel));
  return buildFromDirs(dirs);
}

type Cli =
  | { mode: "write" | "check" }
  | { mode: "emit"; dirs: string[]; root?: string; out: string; runtime: boolean };

export function stripGenCommand(args: string[]): string[] {
  return args[0] === "gen" ? args.slice(1) : args;
}

export function parseCli(args: string[]): { ok: true; cli: Cli } | { ok: false; reason: string } {
  args = stripGenCommand(args);
  if (args.length === 1 && args[0] === "--write") return { ok: true, cli: { mode: "write" } };
  if (args.length === 1 && args[0] === "--check") return { ok: true, cli: { mode: "check" } };
  if (args.includes("--write") || args.includes("--check")) {
    return { ok: false, reason: "usage: rosidl-dts.ts --write|--check" };
  }

  const dirs: string[] = [];
  let out: string | undefined;
  let runtime = false;
  let root: string | undefined;
  for (let i = 0; i < args.length; i++) {
    const arg = args[i]!;
    if (arg === "--package") {
      const value = args[++i];
      if (!value) return { ok: false, reason: "--package requires a directory" };
      dirs.push(value);
    } else if (arg === "--root") {
      const value = args[++i];
      if (!value) return { ok: false, reason: "--root requires a directory" };
      root = value;
    } else if (arg === "--out") {
      const value = args[++i];
      if (!value) return { ok: false, reason: "--out requires a path" };
      out = value;
    } else if (arg === "--runtime") {
      runtime = true;
    } else if (arg === "--help" || arg === "-h") {
      return { ok: false, reason: USER_HELP.trimEnd() };
    } else {
      return { ok: false, reason: `unknown argument ${arg}` };
    }
  }
  if (root && dirs.length) {
    return { ok: false, reason: "use either --package or --root" };
  }
  if (!root && dirs.length === 0) {
    return { ok: false, reason: USER_HELP.trimEnd() };
  }
  if (!out) return { ok: false, reason: "--out is required with --package or --root" };
  if (out.endsWith(".ts") && !out.endsWith(".d.ts")) runtime = true;
  return { ok: true, cli: { mode: "emit", dirs, root, out, runtime } };
}

export function isDirectoryOut(out: string): boolean {
  return out.endsWith("/") || out.endsWith("\\") || !/\.(d\.ts|ts|js)$/.test(out);
}

async function resolveEmitDirs(
  cli: Extract<Cli, { mode: "emit" }>,
): Promise<string[] | { reason: string }> {
  if (cli.root) {
    try {
      return await discoverPackages(cli.root);
    } catch (err) {
      return { reason: err instanceof Error ? err.message : String(err) };
    }
  }
  return cli.dirs;
}

async function writeText(file: string, text: string): Promise<void> {
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, text, "utf8");
}

export function formatStatusLine(built: BuildOk): string {
  const classes = allClasses(built.packages).length;
  return `rosidl-dts: status=ok packages=${built.packages.length} classes=${classes}`;
}

export async function runCli(args: string[], root = process.cwd()): Promise<number> {
  const parsed = parseCli(args);
  if (!parsed.ok) {
    console.error(parsed.reason);
    return 2;
  }
  if (parsed.cli.mode === "write" || parsed.cli.mode === "check") {
    const built = await buildProject(root);
    if (!built.ok) {
      console.error(`rosidl_input_invalid: ${built.reason}`);
      return 1;
    }
    if (parsed.cli.mode === "write") {
      await writeText(path.join(root, TS_OUT_REL), built.ts);
      await writeText(path.join(root, DTS_OUT_REL), built.dts);
      console.log(formatStatusLine(built));
      return 0;
    }
    for (const [rel, text] of [
      [TS_OUT_REL, built.ts],
      [DTS_OUT_REL, built.dts],
    ] as const) {
      let existing: string;
      try {
        existing = await readFile(path.join(root, rel), "utf8");
      } catch {
        console.error(`rosidl_generation_drift: missing committed artifact ${rel}`);
        return 1;
      }
      if (existing !== text) {
        console.error(`rosidl_generation_drift: ${rel}`);
        return 1;
      }
    }
    console.log(formatStatusLine(built));
    return 0;
  }

  const cli = parsed.cli;
  const dirs = await resolveEmitDirs(cli);
  if (!Array.isArray(dirs)) {
    console.error(`rosidl_input_invalid: ${dirs.reason}`);
    return 1;
  }
  if (dirs.length === 0) {
    console.error("rosidl_input_invalid: no interface packages found");
    return 1;
  }
  const built = await buildFromDirs(dirs, USER_BANNER);
  if (!built.ok) {
    console.error(`rosidl_input_invalid: ${built.reason}`);
    return 1;
  }
  const outAbs = path.resolve(root, cli.out);
  if (isDirectoryOut(cli.out)) {
    const ext = cli.runtime ? ".ts" : ".d.ts";
    for (const pkg of built.packages) {
      const text = cli.runtime ? emitTs([pkg], USER_BANNER) : emitDts([pkg], USER_BANNER);
      await writeText(path.join(outAbs, `${pkg.name}${ext}`), text);
    }
    console.log(formatStatusLine(built));
    return 0;
  }
  await writeText(outAbs, cli.runtime ? built.ts : built.dts);
  console.log(formatStatusLine(built));
  return 0;
}

/** Published `npx rcl-web gen` entry. Rejects repo-only --write/--check. */
export async function runUserCli(args: string[], root = process.cwd()): Promise<number> {
  const stripped = stripGenCommand(args);
  if (stripped.length === 0 || stripped[0] === "--help" || stripped[0] === "-h") {
    console.log(USER_HELP.trimEnd());
    return stripped.length === 0 ? 2 : 0;
  }
  if (stripped.includes("--write") || stripped.includes("--check")) {
    console.error("npx rcl-web gen is the application command. --write/--check stay in the repository script.");
    return 2;
  }
  return runCli(stripped, root);
}

function isDirectRepoScript(): boolean {
  return /\/rosidl-dts\.(ts|js)$/.test(import.meta.url);
}

if (import.meta.main && isDirectRepoScript()) {
  const code = await runCli(process.argv.slice(2));
  process.exit(code);
}
